/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as CollectionsIdIndexRouteImport } from './routes/collections.$id.index'
import { Route as CollectionsIdFoldersFolderIdRouteImport } from './routes/collections.$id.folders.$folderId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdIndexRoute = CollectionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsIdRoute,
} as any)
const CollectionsIdFoldersFolderIdRoute =
  CollectionsIdFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => CollectionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/collections/$id': typeof CollectionsIdRouteWithChildren
  '/collections/$id/': typeof CollectionsIdIndexRoute
  '/collections/$id/folders/$folderId': typeof CollectionsIdFoldersFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/collections/$id': typeof CollectionsIdIndexRoute
  '/collections/$id/folders/$folderId': typeof CollectionsIdFoldersFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/collections/$id': typeof CollectionsIdRouteWithChildren
  '/collections/$id/': typeof CollectionsIdIndexRoute
  '/collections/$id/folders/$folderId': typeof CollectionsIdFoldersFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/profile'
    | '/search'
    | '/collections/$id'
    | '/collections/$id/'
    | '/collections/$id/folders/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/profile'
    | '/search'
    | '/collections/$id'
    | '/collections/$id/folders/$folderId'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/profile'
    | '/search'
    | '/collections/$id'
    | '/collections/$id/'
    | '/collections/$id/folders/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  CollectionsIdRoute: typeof CollectionsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id/': {
      id: '/collections/$id/'
      path: '/'
      fullPath: '/collections/$id/'
      preLoaderRoute: typeof CollectionsIdIndexRouteImport
      parentRoute: typeof CollectionsIdRoute
    }
    '/collections/$id/folders/$folderId': {
      id: '/collections/$id/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/collections/$id/folders/$folderId'
      preLoaderRoute: typeof CollectionsIdFoldersFolderIdRouteImport
      parentRoute: typeof CollectionsIdRoute
    }
  }
}

interface CollectionsIdRouteChildren {
  CollectionsIdIndexRoute: typeof CollectionsIdIndexRoute
  CollectionsIdFoldersFolderIdRoute: typeof CollectionsIdFoldersFolderIdRoute
}

const CollectionsIdRouteChildren: CollectionsIdRouteChildren = {
  CollectionsIdIndexRoute: CollectionsIdIndexRoute,
  CollectionsIdFoldersFolderIdRoute: CollectionsIdFoldersFolderIdRoute,
}

const CollectionsIdRouteWithChildren = CollectionsIdRoute._addFileChildren(
  CollectionsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  CollectionsIdRoute: CollectionsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
